(async()=>{
 const service=window.SHROOMS_SERVICE;if(!service)return;
 const config=await service.ready;
 const button=document.createElement('button');button.type='button';button.className='account-trigger';button.textContent=config?'My spots':'Saved spots';
 document.querySelector('header').append(button);
 const dialog=document.createElement('dialog');dialog.className='account-dialog';
 dialog.innerHTML=`<button type="button" class="account-close" aria-label="Close account panel">×</button><div id="account-content"></div><p id="account-error" role="status"></p>`;document.body.append(dialog);
 const content=dialog.querySelector('#account-content'),error=dialog.querySelector('#account-error');
 let user=null,csrf=null,recovery=null;
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function request(route,options={}){return service.request(route,{...options,csrf});}
 function showError(e){error.textContent=(e.name==='TypeError'||e.name==='TimeoutError'||e.name==='AbortError')?'Network connection unavailable. Please try again.':e.message||'Please try again.';}
 dialog.querySelector('.account-close').onclick=()=>dialog.close();
 dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 button.onclick=async()=>{dialog.showModal();error.textContent='';if(!config){content.innerHTML='<h2>Your forest notebook</h2><p>Accounts and private saved spots are available on the hosted website. Start the backend locally to try them.</p>';return;}try{const session=await request('auth/me');user=session.user;csrf=session.csrf;await render();}catch(e){showError(e);}};
 async function render(mode='login'){
  error.textContent='';
  if(!user){
   const register=mode==='register',recover=mode==='recover';
   content.innerHTML=`<div class="kicker">YOUR FOREST NOTEBOOK</div><h2>${register?'Make it yours.':recover?'Recover your account.':'Welcome back.'}</h2><p>Save private spots across Switzerland. Your locations and notes are visible only to you.</p><form id="auth-form"><label>Username<input name="username" required minlength="3" maxlength="32" autocomplete="username" pattern="[a-zA-Z0-9_]+"></label>${recover?'<label>Recovery code<input name="recoveryCode" required autocomplete="off"></label>':''}<label>${recover?'New password':'Password'}<input name="password" type="password" required minlength="12" maxlength="128" autocomplete="${register||recover?'new-password':'current-password'}"></label><small>At least 12 characters. No email address required.</small><button type="submit">${register?'Create account':recover?'Reset password':'Sign in'}</button></form><div class="account-actions"><button data-mode="${register?'login':'register'}">${register?'Sign in instead':'Create an account'}</button><button data-mode="recover">Use a recovery code</button></div>`;
   content.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>render(b.dataset.mode));
   content.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=e.target.querySelector('[type=submit]');submit.disabled=true;error.textContent='';try{const result=await request(`auth/${register?'register':recover?'recover':'login'}`,{method:'POST',body:Object.fromEntries(new FormData(e.target))});user=result.user;csrf=result.csrf;recovery=result.recoveryCode||null;await render();}catch(e){showError(e);}finally{submit.disabled=false;}};
   return;
  }
  const {spots}=await request('spots');
  content.innerHTML=`<div class="kicker"><span>PRIVATE TO</span> <span data-no-translate>${escape(user.username)}</span></div><h2>Your forest notebook.</h2>${recovery?`<div class="recovery-notice"><strong>Save your recovery code now</strong><p>This is your only password-recovery method. Store it somewhere safe. It is shown only once.</p><code>${escape(recovery)}</code><button id="recovery-saved">I saved it</button></div>`:''}<button id="save-current">Save selected forest cell</button><p>${spots.length} / 500 spots · private by default</p><div class="saved-spots">${spots.map(s=>`<article><button class="open-spot" data-id="${s.id}"><strong data-no-translate>${escape(s.name)}</strong><small>${escape(s.species)} · ${s.lat.toFixed(4)}, ${s.lon.toFixed(4)}</small></button><p data-no-translate>${escape(s.notes)}</p><div class="account-actions"><button class="edit-spot" data-id="${s.id}">Edit</button><button class="delete-spot" data-id="${s.id}">Delete</button></div></article>`).join('')||'<p>No saved spots yet. Choose a forest on the map, then save it here.</p>'}</div><div class="account-actions"><button id="export-spots">Export my spots</button><button id="logout">Sign out</button><button id="delete-account">Delete account</button></div>`;
  if(recovery)content.querySelector('#recovery-saved').onclick=()=>{recovery=null;render();};
  content.querySelector('#save-current').onclick=()=>{const c=window.SHROOMS_SELECTED?.();if(!c){error.textContent='Choose a forest cell on the map first.';return;}editor({name:c.name,lat:c.lat,lon:c.lon,species:c.species,cellId:`${c.region}:${c.id}`,notes:''});};
  content.querySelectorAll('.open-spot').forEach(b=>b.onclick=()=>{const spot=spots.find(s=>s.id===b.dataset.id),region=spot.cellId?.split(':')[0];if(region&&region!==window.SHROOMS_REGION){sessionStorage.setItem('shrooms-open-spot',JSON.stringify(spot));const url=new URL(location.href);url.searchParams.set('region',region);url.hash='explore';location.href=url;}else{window.dispatchEvent(new CustomEvent('shrooms:open-spot',{detail:spot}));dialog.close();}});
  content.querySelectorAll('.edit-spot').forEach(b=>b.onclick=()=>editor(spots.find(s=>s.id===b.dataset.id)));
  content.querySelectorAll('.delete-spot').forEach(b=>b.onclick=async()=>{if(!confirm(window.SHROOMS_I18N.t('Delete this saved spot?')))return;try{await request(`spots/${b.dataset.id}`,{method:'DELETE'});await render();}catch(e){showError(e);}});
  content.querySelector('#logout').onclick=async()=>{try{await request('auth/logout',{method:'POST'});user=null;csrf=null;recovery=null;await render();}catch(e){showError(e);}};
  content.querySelector('#export-spots').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exported:new Date().toISOString(),spots},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='shrooms-private-spots.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  content.querySelector('#delete-account').onclick=()=>{content.innerHTML='<h2>Delete your account?</h2><p>This permanently deletes your account, saved spots and sessions. Export your spots first if you want a copy.</p><form><label>Confirm your password<input name="password" type="password" required autocomplete="current-password"></label><button type="submit">Permanently delete account</button><button type="button" id="cancel-delete">Cancel</button></form>';content.querySelector('#cancel-delete').onclick=()=>render();content.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await request('account',{method:'DELETE',body:Object.fromEntries(new FormData(e.target))});user=null;csrf=null;recovery=null;render();}catch(e){showError(e);}};};
 }
 function editor(spot){
  content.innerHTML=`<h2>${spot.id?'Edit spot':'Save this forest.'}</h2><p>This location stays private to your account.</p><form id="spot-form"><label>Name<input name="name" value="${escape(spot.name)}" required maxlength="100"></label><label>Notes<textarea name="notes" rows="4" maxlength="2000">${escape(spot.notes||'')}</textarea></label><small>${spot.lat.toFixed(5)}, ${spot.lon.toFixed(5)} · ${escape(spot.species)}</small><button type="submit">Save spot</button><button type="button" id="cancel-spot">Cancel</button></form>`;
  content.querySelector('#cancel-spot').onclick=()=>render();content.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await request(spot.id?`spots/${spot.id}`:'spots',{method:spot.id?'PUT':'POST',body:{...spot,...Object.fromEntries(new FormData(e.target))}});await render();}catch(e){showError(e);}};
 }
 window.addEventListener('shrooms:ready',()=>{try{const saved=sessionStorage.getItem('shrooms-open-spot');if(saved){sessionStorage.removeItem('shrooms-open-spot');window.dispatchEvent(new CustomEvent('shrooms:open-spot',{detail:JSON.parse(saved)}));}}catch{}});
})();
