// Approximate exploration anchors, not verified stand boundaries or collection coordinates.
window.MYCO_DATA = {
  species: {
    porcini: { name: 'Porcini', local: 'Steinpilz', latin: 'Boletus edulis', icon: '◕', months: [7, 8, 9, 10], habitat: { conifer: 0.92, mixed: 1, beech: 0.82, broadleaf: 0.64, edge: 0.32 }, temp: [9, 19], note: 'Often associated with mature beech, spruce and other trees.' },
    chanterelle: { name: 'Chanterelle', local: 'Eierschwamm', latin: 'Cantharellus cibarius', icon: '✦', months: [6, 7, 8, 9, 10], habitat: { conifer: 0.7, mixed: 1, beech: 0.83, broadleaf: 0.8, edge: 0.4 }, temp: [11, 21], note: 'Often associated with mixed and broadleaf woods, sometimes conifers.' },
    horn: { name: 'Horn of plenty', local: 'Totentrompete', latin: 'Craterellus cornucopioides', icon: '◡', months: [8, 9, 10, 11], habitat: { conifer: 0.28, mixed: 0.75, beech: 1, broadleaf: 0.94, edge: 0.35 }, temp: [8, 18], note: 'Often found in deciduous woods, especially beneath beech.' },
    parasol: { name: 'Parasol', local: 'Riesenschirmling', latin: 'Macrolepiota procera', icon: '☂', months: [7, 8, 9, 10, 11], habitat: { conifer: 0.25, mixed: 0.52, beech: 0.48, broadleaf: 0.5, edge: 1 }, temp: [11, 22], note: 'Favors open woodland edges, clearings and grassy places.' }
  },
  sites: [
    { id:'albis', name:'Albis ridge', region:'Knonaueramt', lat:47.285, lon:8.525, habitat:'mixed', moisture:'moderate', elevation:'650–900 m', trees:'Mixed beech & conifer', clue:'Wooded slopes and changing elevation create varied conditions.', access:'Explore established public paths around Albispass.' },
    { id:'uetliberg', name:'Uetliberg woods', region:'Zürich–Albis', lat:47.347, lon:8.493, habitat:'beech', moisture:'moderate', elevation:'500–870 m', trees:'Beech woodland', clue:'A broadleaf ridge close to the city, with shaded slopes.', access:'Use marked trails; check local protection zones.' },
    { id:'pfannenstiel', name:'Pfannenstiel', region:'Meilen district', lat:47.286, lon:8.665, habitat:'mixed', moisture:'moderate', elevation:'550–850 m', trees:'Mixed woodland', clue:'Long wooded ridge with both sheltered and exposed aspects.', access:'Many signed walking routes cross the ridge.' },
    { id:'zuerichberg', name:'Zürichberg & Adlisberg', region:'Zürich district', lat:47.389, lon:8.589, habitat:'beech', moisture:'moderate', elevation:'480–700 m', trees:'Broadleaf & beech', clue:'Accessible shaded woodland with varied edges.', access:'Stay aware of recreation and conservation rules.' },
    { id:'laegern', name:'Lägern foothills', region:'Dielsdorf', lat:47.488, lon:8.443, habitat:'beech', moisture:'drier', elevation:'500–800 m', trees:'Beech & broadleaf', clue:'A limestone ridge; drier sites can temper rain signals.', access:'Steep terrain: choose marked routes.' },
    { id:'irchel', name:'Irchel', region:'Winterthur district', lat:47.551, lon:8.617, habitat:'mixed', moisture:'moderate', elevation:'450–690 m', trees:'Mixed woodland', clue:'A forested ridge amid the northern agricultural landscape.', access:'Approach from public paths around the ridge.' },
    { id:'kyburg', name:'Kyburg woods', region:'Winterthur district', lat:47.456, lon:8.744, habitat:'mixed', moisture:'wetter', elevation:'500–700 m', trees:'Mixed woodland', clue:'Valley slopes and stream corridors may retain moisture.', access:'Check local reserve boundaries before collecting.' },
    { id:'toess', name:'Töss valley slopes', region:'Zürcher Oberland', lat:47.350, lon:8.895, habitat:'conifer', moisture:'wetter', elevation:'600–950 m', trees:'Conifer & mixed', clue:'Cooler upland woods and sheltered valley sides.', access:'Use trails around Bauma and the Töss valley.' },
    { id:'hoernli', name:'Hörnli approach', region:'Zürcher Oberland', lat:47.375, lon:8.981, habitat:'conifer', moisture:'wetter', elevation:'700–1100 m', trees:'Conifer & mixed', clue:'Higher, cooler forest habitat at the eastern edge of the canton.', access:'Check canton borders and local rules on your route.' },
    { id:'bachtel', name:'Bachtel slopes', region:'Hinwil district', lat:47.305, lon:8.885, habitat:'mixed', moisture:'wetter', elevation:'650–1050 m', trees:'Mixed upland woodland', clue:'Upland forest with variable exposure and rainfall.', access:'Follow signed hiking paths and observe reserves.' },
    { id:'stammheim', name:'Stammheim woods', region:'Weinland', lat:47.631, lon:8.790, habitat:'broadleaf', moisture:'moderate', elevation:'450–650 m', trees:'Broadleaf woodland', clue:'Northern lowland woodland in a warmer setting.', access:'Look for public forest paths around Stammheim.' },
    { id:'andelfingen', name:'Andelfingen woodland', region:'Weinland', lat:47.600, lon:8.690, habitat:'edge', moisture:'drier', elevation:'380–550 m', trees:'Woodland edge & clearing', clue:'Open edges may suit grassland and clearing species.', access:'Avoid fields and private land.' },
    { id:'hochwacht', name:'Hochwacht ridge', region:'Uster district', lat:47.370, lon:8.720, habitat:'mixed', moisture:'moderate', elevation:'500–800 m', trees:'Mixed woodland', clue:'A wooded transition between the lake basin and Oberland.', access:'Use public footpaths around the ridge.' }
  ]
};
