window.SHROOMS_SPECIES = {
  porcini: { name: 'Porcini', local: 'Steinpilz', latin: 'Boletus edulis', months: [7,8,9,10], temp: [9,19], host: { beech: 1, oak: .75, conifer: .9, other: .5 }, canopy: 'closed', note: 'Tree partners, a sheltered canopy and moisture after rain.' },
  chanterelle: { name: 'Chanterelle', local: 'Eierschwamm', latin: 'Cantharellus cibarius', months: [6,7,8,9,10], temp: [11,21], host: { beech: .85, oak: 1, conifer: .8, other: .6 }, canopy: 'closed', note: 'Broadleaf or mixed forest. Soil acidity is not yet included.' },
  horn: { name: 'Horn of plenty', local: 'Totentrompete', latin: 'Craterellus cornucopioides', months: [8,9,10,11], temp: [8,18], host: { beech: 1, oak: .95, conifer: .15, other: .5 }, canopy: 'closed', note: 'A preference for broadleaf woods, especially beech and oak.' },
  parasol: { name: 'Parasol', local: 'Riesenschirmling', latin: 'Macrolepiota procera', months: [7,8,9,10,11], temp: [11,22], host: null, canopy: 'open', note: 'More open canopy and forest edges. Open grassland is outside this forest map.' },
  bay: { name: 'Bay bolete', local: 'Maronenröhrling', latin: 'Imleria badia', months: [7,8,9,10,11], temp: [8,18], host: { beech: .7, oak: .6, conifer: 1, other: .4 }, canopy: 'closed', note: 'Conifer and mixed woodland. Acidic soil preference is not yet mapped.' },
  hedgehog: { name: 'Wood hedgehog', local: 'Semmelstoppelpilz', latin: 'Hydnum repandum', months: [8,9,10,11], temp: [7,17], host: { beech: 1, oak: .8, conifer: .85, other: .7 }, canopy: 'closed', note: 'Damp broadleaf and mixed woods; moss and leaf litter are not yet mapped.' },
  saffron: { name: 'Saffron milkcap', local: 'Echter Reizker', latin: 'Lactarius deliciosus', months: [8,9,10,11], temp: [8,18], host: { beech: .05, oak: .05, conifer: .05, other: .05 }, requiredTree: 'pine', canopy: 'open', note: 'Pine partner: uses mapped pine share, not general conifer cover. Soil chemistry is not yet included.' }
};
