/* Columns: English, Swiss Standard German, French, Italian, Rumantsch Grischun.
   Place names, scientific names and private notebook content retain their original form. */
window.SHROOMS_MESSAGES=String.raw`
Use my location|Meinen Standort verwenden|Utiliser ma position|Usa la mia posizione|Dovra mia posiziun
Hide location|Standort ausblenden|Masquer ma position|Nascondi posizione|Zuppenta la posiziun
Your position stays in this tab.|Dein Standort bleibt in diesem Tab.|Votre position reste dans cet onglet.|La tua posizione resta in questa scheda.|Tia posiziun resta en quest tab.
Your location|Dein Standort|Votre position|La tua posizione|Tia posiziun
Finding your location…|Standort wird ermittelt…|Recherche de votre position…|Ricerca della posizione…|Tschertgar tia posiziun…
Location accuracy: about {distance} m.|Standortgenauigkeit: etwa {distance} m.|Précision de la position : environ {distance} m.|Precisione della posizione: circa {distance} m.|Precisiun da la posiziun: circa {distance} m.
Location needs HTTPS or localhost and a supported browser.|Der Standort benötigt HTTPS oder localhost und einen unterstützten Browser.|La localisation nécessite HTTPS ou localhost et un navigateur compatible.|La posizione richiede HTTPS o localhost e un browser compatibile.|La posiziun dovra HTTPS u localhost ed in navigatur cumpatibel.
Outside this map. Choose Switzerland or your canton, then try again.|Ausserhalb dieser Karte. Wähle die Schweiz oder deinen Kanton und versuche es erneut.|Hors de cette carte. Choisissez la Suisse ou votre canton, puis réessayez.|Fuori da questa mappa. Scegli la Svizzera o il tuo cantone e riprova.|Ordaifer questa charta. Tscherna la Svizra u tes chantun ed emprova danovamain.
Your location is outside the Swiss map coverage.|Dein Standort liegt ausserhalb der Schweizer Kartenabdeckung.|Votre position est hors de la couverture de la carte suisse.|La tua posizione è fuori dalla copertura della mappa svizzera.|Tia posiziun è ordaifer la cuverta da la charta svizra.
Location permission denied. Allow it in your browser to try again.|Standortzugriff verweigert. Erlaube ihn im Browser und versuche es erneut.|Accès à la position refusé. Autorisez-le dans votre navigateur pour réessayer.|Accesso alla posizione negato. Consentilo nel browser e riprova.|Access a la posiziun refusà. Permetta el en tes navigatur ed emprova danovamain.
Location timed out. Please try again.|Zeitüberschreitung beim Standort. Bitte erneut versuchen.|Délai de localisation dépassé. Veuillez réessayer.|Tempo di localizzazione scaduto. Riprova.|Il temp per la posiziun è scadì. Emprova danovamain.
Location unavailable. Please try again.|Standort nicht verfügbar. Bitte erneut versuchen.|Position indisponible. Veuillez réessayer.|Posizione non disponibile. Riprova.|Posiziun betg disponibla. Emprova danovamain.
Language|Sprache|Langue|Lingua|Lingua
shrooms — follow the fungi|shrooms — folge den Pilzen|shrooms — suivez les champignons|shrooms — segui i funghi|shrooms — suonda ils bulieus
shrooms home|shrooms Startseite|Accueil shrooms|Pagina iniziale shrooms|Pagina iniziala shrooms
Main navigation|Hauptnavigation|Navigation principale|Navigazione principale|Navigaziun principala
The map|Die Karte|La carte|La mappa|La charta
Behind the colors|Hinter den Farben|Derrière les couleurs|Dietro i colori|Davos las colurs
Before you go|Vor dem Aufbruch|Avant de partir|Prima di partire|Avant che partir
SWITZERLAND|SCHWEIZ|SUISSE|SVIZZERA|SVIZRA
Switzerland|Schweiz|Suisse|Svizzera|Svizra
A FIELD GUIDE FOR THE WANDERERS|EIN WEGWEISER FÜR ENTDECKER|UN GUIDE POUR LES PROMENEURS|UNA GUIDA PER CHI ESPLORA|IN GUID PER EXPLORATURS
Follow|Folge|Suivez|Segui|Suonda
the|den|les|i|ils
fungi.|Pilzen.|champignons.|funghi.|bulieus.
A little rain. The right trees. A promising patch of earth. Explore the conditions that make Switzerland’s forests a little more magical.|Etwas Regen. Die richtigen Bäume. Ein vielversprechendes Stück Wald. Entdecke die Bedingungen, die Schweizer Wälder noch etwas zauberhafter machen.|Un peu de pluie. Les bons arbres. Un coin de forêt prometteur. Explorez les conditions qui rendent les forêts suisses un peu plus magiques.|Un po’ di pioggia. Gli alberi giusti. Un angolo di bosco promettente. Esplora le condizioni che rendono i boschi svizzeri ancora più magici.|In pau plievgia. Las plantas adattadas. In toc guaud empermettent. Explorescha las cundiziuns che rendan ils guauds svizzers anc in pau pli magics.
Find your forest|Finde deinen Wald|Trouvez votre forêt|Trova il tuo bosco|Chatta tes guaud
ROOTED IN REAL DATA|AUF ECHTEN DATEN AUFGEBAUT|FONDÉ SUR DES DONNÉES RÉELLES|BASATO SU DATI REALI|BASÀ SIN DATAS REALAS
Wild colors.|Wilde Farben.|Couleurs sauvages.|Colori selvaggi.|Colurs selvadias.
Earthly clues.|Natürliche Hinweise.|Indices naturels.|Indizi naturali.|Indizis natirals.
Forest|Wald|Forêt|Bosco|Guaud
moisture|Feuchtigkeit|humidité|umidità|umiditad
terrain|Gelände|relief|terreno|terren
forest cells|Waldzellen|cellules forestières|celle forestali|cellas da guaud
Official Swiss forest & terrain data|Offizielle Schweizer Wald- und Geländedaten|Données suisses officielles sur les forêts et le relief|Dati ufficiali svizzeri su boschi e terreno|Datas uffizialas svizras davart guaud e terren
Open-Meteo moisture & weather|Feuchtigkeit und Wetter von Open-Meteo|Humidité et météo Open-Meteo|Umidità e meteo Open-Meteo|Umiditad ed aura dad Open-Meteo
✳ Switzerland|✳ Schweiz|✳ Suisse|✳ Svizzera|✳ Svizra
regional detail|Regionale Details|détails régionaux|dettagli regionali|detagls regiunals
01 / READ THE FOREST|01 / DEN WALD LESEN|01 / LIRE LA FORÊT|01 / LEGGERE IL BOSCO|01 / LEGER IL GUAUD
Where the conditions come together.|Wo die Bedingungen zusammenpassen.|Là où les conditions se rencontrent.|Dove le condizioni si incontrano.|Nua che las cundiziuns sa scuntran.
Choose a mushroom. Zoom from regional summaries into regional forest detail. Click a forest patch to see its evidence.|Wähle einen Pilz. Zoome von der Übersicht bis zu einzelnen Waldflächen. Klicke auf eine Fläche, um ihre Datengrundlage zu sehen.|Choisissez un champignon. Zoomez de la vue régionale aux détails forestiers. Cliquez sur une zone pour consulter ses données.|Scegli un fungo. Passa dalla panoramica regionale ai dettagli del bosco. Clicca su un’area per vedere i dati.|Tscherna in bulieu. Zooma da la survista regiunala als detagls dal guaud. Clicca sin ina surfatscha per vesair sias datas.
EXPLORE A REGION|REGION ENTDECKEN|EXPLORER UNE RÉGION|ESPLORA UNA REGIONE|EXPLORAR INA REGIUN
Map region|Kartenregion|Région de la carte|Regione della mappa|Regiun da la charta
On your radar|Im Blick|À explorer|Da esplorare|Da explorar
Mushroom species|Pilzart|Espèce de champignon|Specie di fungo|Spezia da bulieu
Find a municipality|Gemeinde suchen|Chercher une commune|Cerca un comune|Tschertgar ina vischnanca
e.g. Winterthur|z. B. Winterthur|p. ex. Winterthur|ad es. Winterthur|p. ex. Winterthur
PROMISING CELLS|VIELVERSPRECHENDE ZELLEN|CELLULES PROMETTEUSES|CELLE PROMETTENTI|CELLAS EMPERMETTENTAS
Ranked forest cells|Waldzellen nach Bewertung|Cellules forestières classées|Celle forestali ordinate|Cellas da guaud ordinadas
Ranked from the visible map. Searching a municipality looks across this region.|Nach sichtbarem Kartenausschnitt geordnet. Die Gemeindesuche durchsucht die ganze Region.|Classement selon la carte visible. La recherche d’une commune couvre toute la région.|Ordinate in base alla mappa visibile. La ricerca di un comune copre tutta la regione.|Ordinadas tenor la charta visibla. La tschertga d’ina vischnanca cumpiglia l’entira regiun.
Navigable forest habitat map of Switzerland|Navigierbare Waldhabitatkarte der Schweiz|Carte interactive des habitats forestiers suisses|Mappa navigabile degli habitat forestali svizzeri|Charta navigabla dals habitats da guaud svizzers
Loading data…|Daten werden geladen…|Chargement des données…|Caricamento dei dati…|Chargiar las datas…
Refresh weather|Wetter aktualisieren|Actualiser la météo|Aggiorna il meteo|Actualisar l’aura
Show the whole region|Ganze Region anzeigen|Afficher toute la région|Mostra tutta la regione|Mussar l’entira regiun
Whole region|Ganze Region|Toute la région|Tutta la regione|Entira regiun
Map display|Kartendarstellung|Affichage de la carte|Visualizzazione della mappa|Visualisaziun da la charta
◉ Heatmap|◉ Wärmekarte|◉ Carte thermique|◉ Mappa termica|◉ Charta da chalur
♧ Forest type|♧ Waldtyp|♧ Type de forêt|♧ Tipo di bosco|♧ Tip da guaud
Some forest tiles could not load. Pan the map to retry.|Einige Waldkacheln konnten nicht geladen werden. Verschiebe die Karte, um es erneut zu versuchen.|Certaines tuiles forestières n’ont pas pu être chargées. Déplacez la carte pour réessayer.|Alcune tessere forestali non sono state caricate. Sposta la mappa per riprovare.|Intginas parts da la charta n’han betg pudì vegnir chargiadas. Sposta la charta per empruvar danovamain.
HABITAT SIGNAL|HABITAT-SIGNAL|INDICE D’HABITAT|SEGNALE DELL’HABITAT|SIGNAL DA L’HABITAT
FOREST TYPE|WALDTYP|TYPE DE FORÊT|TIPO DI BOSCO|TIP DA GUAUD
Lower|Schwächer|Plus faible|Più debole|Pli flaivel
Stronger|Stärker|Plus fort|Più forte|Pli ferm
Contrast scaled across this region · pink = strongest|Kontrast über die ganze Region · Pink = stärkstes Signal|Contraste à l’échelle régionale · rose = signal maximal|Contrasto su tutta la regione · rosa = segnale più forte|Contrast per l’entira regiun · rosa = signal il pli ferm
Conifer|Nadelwald|Résineux|Conifere|Guaud da coniferas
Mixed|Mischwald|Mixte|Misto|Guaud maschadà
Broadleaf|Laubwald|Feuillus|Latifoglie|Guaud da feglia
Unknown|Unbekannt|Inconnu|Sconosciuto|Nunenconuschent
unknown|unbekannt|inconnu|sconosciuto|nunenconuschent
Mapped protected areas|Kartierte Schutzgebiete|Zones protégées cartographiées|Aree protette cartografate|Territoris protegids cartografads
Loading reserve boundaries…|Schutzgebietsgrenzen werden geladen…|Chargement des limites des réserves…|Caricamento dei confini delle riserve…|Chargiar ils cunfins da las reservas…
Partial coverage only. Unmarked areas may have other protections.|Nur teilweise Abdeckung. Auch unmarkierte Gebiete können geschützt sein.|Couverture partielle. Des zones non marquées peuvent aussi être protégées.|Copertura parziale. Anche le aree non segnalate possono essere protette.|Mo cuverta parziala. Territoris betg marcads pon er esser protegids.
Retry|Erneut versuchen|Réessayer|Riprova|Empruvar danovamain
Colors show modeled habitat suitability, not known finds or a calibrated probability. Habitat scores also cover forest reserves, where collecting may be forbidden. Check local protection rules before collecting. Unshaded areas have no estimate.|Die Farben zeigen modellierte Habitateignung, keine bekannten Funde oder kalibrierte Wahrscheinlichkeit. Auch Waldreservate werden bewertet; dort kann Sammeln verboten sein. Prüfe die lokalen Schutzregeln. Ungefärbte Flächen haben keine Schätzung.|Les couleurs indiquent une aptitude modélisée de l’habitat, pas des trouvailles ni une probabilité calibrée. Les réserves sont aussi évaluées ; la cueillette peut y être interdite. Vérifiez les règles locales. Les zones sans couleur n’ont pas d’estimation.|I colori indicano l’idoneità modellata dell’habitat, non ritrovamenti o probabilità calibrate. Sono valutate anche le riserve, dove la raccolta può essere vietata. Verifica le norme locali. Le aree senza colore non hanno una stima.|Las colurs mussan l’adattaziun modelada da l’habitat, betg chats enconuschents u ina probabilitad calibrada. Er las reservas vegnan valitadas; là po la racolta esser scumandada. Controllescha las reglas localas. Surfatschas senza colur n’han nagina stimaziun.
02 / BEHIND THE COLORS|02 / HINTER DEN FARBEN|02 / DERRIÈRE LES COULEURS|02 / DIETRO I COLORI|02 / DAVOS LAS COLURS
No secret spots.|Keine geheimen Fundorte.|Pas de coins secrets.|Nessun posto segreto.|Nagins lieus secrets.
Just better clues.|Einfach bessere Hinweise.|Juste de meilleurs indices.|Solo indizi migliori.|Mo megliers indizis.
Every patch starts with mapped forest. Every color has a reason.|Jede Fläche beginnt mit kartiertem Wald. Jede Farbe hat einen Grund.|Chaque zone part d’une forêt cartographiée. Chaque couleur a une raison.|Ogni area parte da un bosco cartografato. Ogni colore ha un motivo.|Mintga surfatscha cumenza cun guaud cartografà. Mintga colur ha in motiv.
01 / THE PLACE|01 / DER ORT|01 / LE LIEU|01 / IL LUOGO|01 / IL LIEU
Forest & terrain|Wald und Gelände|Forêt et relief|Bosco e terreno|Guaud e terren
Actual forest stands, canopy coverage, tree mix, slope and aspect.|Kartierte Waldbestände, Kronendeckung, Baumarten, Neigung und Exposition.|Peuplements cartographiés, couvert, essences, pente et exposition.|Popolamenti cartografati, copertura, composizione, pendenza ed esposizione.|Guaud cartografà, cuverta da tschimas, maschaida da plantas, pendenza ed exposiziun.
02 / THE MOMENT|02 / DER ZEITPUNKT|02 / LE MOMENT|02 / IL MOMENTO|02 / IL MUMENT
Moisture & weather|Feuchtigkeit und Wetter|Humidité et météo|Umidità e meteo|Umiditad ed aura
14 days of rain, recent soil moisture and humidity, 7-day temperature.|14 Tage Regen, aktuelle Boden- und Luftfeuchtigkeit, 7-Tage-Temperatur.|14 jours de pluie, humidité récente du sol et de l’air, température sur 7 jours.|14 giorni di pioggia, umidità recente del suolo e dell’aria, temperatura su 7 giorni.|14 dis plievgia, umiditad recenta dal terren e da l’aria, temperatura da 7 dis.
03 / THE MUSHROOM|03 / DER PILZ|03 / LE CHAMPIGNON|03 / IL FUNGO|03 / IL BULIEU
Species preferences|Vorlieben der Arten|Préférences des espèces|Preferenze delle specie|Preferenzas da las spezias
Different tree partners, canopy preferences, temperatures and seasons.|Unterschiedliche Baumpartner, Kronendeckung, Temperaturen und Jahreszeiten.|Différents arbres partenaires, couverts, températures et saisons.|Diversi alberi ospiti, coperture, temperature e stagioni.|Differents partenaris da plantas, cuvertas, temperaturas e stagiuns.
See the model & its limits|Modell und Grenzen ansehen|Voir le modèle et ses limites|Scopri il modello e i suoi limiti|Vesair il model e ses cunfins
REAL SOURCES. NO INVENTED HOTSPOTS.|ECHTE QUELLEN. KEINE ERFUNDENEN FUNDORTE.|DES SOURCES RÉELLES. AUCUN COIN INVENTÉ.|FONTI REALI. NESSUN POSTO INVENTATO.|FUNTAUNAS REALAS. NAGINS LIEUS INVENTADS.
GIS-ZH / FOREST STANDS|GIS-ZH / WALDBESTÄNDE|GIS-ZH / PEUPLEMENTS FORESTIERS|GIS-ZH / POPOLAMENTI FORESTALI|GIS-ZH / GUAUDS
What grows here ↗|Was hier wächst ↗|Ce qui pousse ici ↗|Cosa cresce qui ↗|Tge che crescha qua ↗
Aerial stand polygons, tree shares, canopy coverage and survey dates.|Luftbild-Waldbestände, Baumartenanteile, Kronendeckung und Erhebungsdaten.|Polygones issus de vues aériennes, essences, couvert et dates de relevé.|Poligoni da rilievi aerei, quote di alberi, copertura e date dei rilievi.|Poligons da fotografias or da l’aria, parts da plantas, cuverta e datas da relevaziun.
SWISS FOREST & TERRAIN DATA|SCHWEIZER WALD- UND GELÄNDEDATEN|DONNÉES SUISSES FORÊT ET RELIEF|DATI SVIZZERI SU BOSCHI E TERRENO|DATAS SVIZRAS DA GUAUD E TERREN
The shape of the land ↗|Die Form der Landschaft ↗|La forme du terrain ↗|La forma del terreno ↗|La furma dal terren ↗
swissTLMRegio forest boundaries, FOEN / WSL forest mix, DHM25/200 terrain.|Waldgrenzen: swissTLMRegio; Waldmischung: BAFU / WSL; Gelände: DHM25/200.|Limites forestières : swissTLMRegio ; mélange : OFEV / WSL ; relief : DHM25/200.|Confini forestali: swissTLMRegio; composizione: UFAM / WSL; terreno: DHM25/200.|Cunfins dal guaud: swissTLMRegio; maschaida: UFAM / WSL; terren: DHM25/200.
OPEN-METEO / WEATHER|OPEN-METEO / WETTER|OPEN-METEO / MÉTÉO|OPEN-METEO / METEO|OPEN-METEO / AURA
What the weather’s doing ↗|Was das Wetter macht ↗|Ce que fait la météo ↗|Cosa fa il tempo ↗|Tge che fa l’aura ↗
Regional weather anchors. Hosted mode refreshes a shared snapshot automatically; static mode uses a bundled snapshot and optional refresh. Weather older than 48 hours is omitted.|Regionale Wetterpunkte. Der Server aktualisiert einen gemeinsamen Datenstand automatisch; die statische Version nutzt mitgelieferte Daten und eine optionale Aktualisierung. Wetterdaten über 48 Stunden werden ausgelassen.|Points météo régionaux. Le serveur actualise automatiquement un instantané partagé ; la version statique utilise un instantané fourni, actualisable. Les données de plus de 48 heures sont exclues.|Punti meteo regionali. Il server aggiorna automaticamente dati condivisi; la versione statica usa dati inclusi con aggiornamento facoltativo. I dati oltre 48 ore sono esclusi.|Puncts d’aura regiunals. Il server actualisescha automaticamain datas communablas; la versiun statica dovra datas inclusas cun actualisaziun facultativa. Datas pli veglias che 48 uras vegnan omessas.
03 / TREAD LIGHTLY|03 / ACHTSAM UNTERWEGS|03 / MARCHER AVEC RESPECT|03 / CAMMINA CON RISPETTO|03 / VIAGIAR CUN RESPECT
Good vibes.|Gute Stimmung.|De bonnes ondes.|Buone sensazioni.|Buna atmosfera.
Gentle footprints.|Sanfte Spuren.|Des pas légers.|Passi leggeri.|Pass levs.
Collection rules vary by canton and municipality. Check the rules for your selected location before collecting. Protected areas may prohibit collecting.|Sammelregeln unterscheiden sich je nach Kanton und Gemeinde. Prüfe vor dem Sammeln die örtlichen Regeln. In Schutzgebieten kann Sammeln verboten sein.|Les règles varient selon le canton et la commune. Vérifiez celles du lieu choisi avant la cueillette. Elle peut être interdite dans les zones protégées.|Le norme variano secondo il cantone e il comune. Verifica quelle del luogo scelto prima della raccolta. Nelle aree protette può essere vietata.|Las reglas da racolta varieschan tenor chantun e vischnanca. Controllescha las reglas dal lieu tschernì avant la racolta. En territoris protegids po ella esser scumandada.
Check cantonal collecting rules ↗|Kantonale Sammelregeln prüfen ↗|Consulter les règles cantonales ↗|Consulta le norme cantonali ↗|Controllar las reglas chantunalas ↗
Check today’s collecting status|Heutige Sammelregeln prüfen|Vérifier les règles du jour|Verifica le regole di oggi|Controllar las reglas dad oz
This map cannot identify mushrooms. Have your collection checked by a local|Diese Karte kann keine Pilze bestimmen. Lass deine Sammlung prüfen bei einer örtlichen|Cette carte ne permet pas d’identifier les champignons. Faites contrôler votre récolte par un service local de|Questa mappa non identifica i funghi. Fai controllare la raccolta da un servizio locale di|Questa charta na po betg identifitgar bulieus. Lascha controllar tia racolta tar in post local da
Pilzkontrollstelle ↗|Pilzkontrollstelle ↗|contrôle des champignons ↗|controllo dei funghi ↗|controlla da bulieus ↗
before eating.|bevor du sie isst.|avant de les consommer.|prima di consumarli.|avant che mangiar els.
For curious walks and strange little wonders.|Für neugierige Spaziergänge und kleine Wunder.|Pour des balades curieuses et de petites merveilles.|Per passeggiate curiose e piccole meraviglie.|Per spassegiadas mirvegliusas e pitschnas miraclas.
Forest & terrain: GIS-ZH|Wald und Gelände: GIS-ZH|Forêt et relief : GIS-ZH|Boschi e terreno: GIS-ZH|Guaud e terren: GIS-ZH
Swiss data: © swisstopo · FOEN / WSL|Schweizer Daten: © swisstopo · BAFU / WSL|Données suisses : © swisstopo · OFEV / WSL|Dati svizzeri: © swisstopo · UFAM / WSL|Datas svizras: © swisstopo · UFAM / WSL
Weather: Open-Meteo|Wetter: Open-Meteo|Météo : Open-Meteo|Meteo: Open-Meteo|Aura: Open-Meteo
Roads & places: © OpenStreetMap contributors|Strassen und Orte: © OpenStreetMap-Mitwirkende|Routes et lieux : © contributeurs OpenStreetMap|Strade e luoghi: © contributori OpenStreetMap|Vias e lieus: © contribuents OpenStreetMap
`.trim().split('\n').map(line=>line.split('|'));
window.SHROOMS_MESSAGES.push(...String.raw`
My spots|Meine Orte|Mes coins|I miei luoghi|Mes lieus
Saved spots|Gespeicherte Orte|Coins enregistrés|Luoghi salvati|Lieus memorisads
Close account panel|Kontofenster schliessen|Fermer le compte|Chiudi il pannello account|Serrar la fanestra dal conto
Your forest notebook|Dein Waldnotizbuch|Votre carnet forestier|Il tuo taccuino del bosco|Tes carnet dal guaud
Your forest notebook.|Dein Waldnotizbuch.|Votre carnet forestier.|Il tuo taccuino del bosco.|Tes carnet dal guaud.
YOUR FOREST NOTEBOOK|DEIN WALDNOTIZBUCH|VOTRE CARNET FORESTIER|IL TUO TACCUINO DEL BOSCO|TES CARNET DAL GUAUD
Accounts and private saved spots are available on the hosted website. Start the backend locally to try them.|Konten und private Orte sind auf der Website mit Server verfügbar. Starte den lokalen Server, um sie auszuprobieren.|Les comptes et coins privés sont disponibles sur le site avec serveur. Lancez le serveur local pour les essayer.|Gli account e i luoghi privati sono disponibili sul sito con server. Avvia il server locale per provarli.|Contos e lieus privats èn disponibels sin la pagina cun server. Aviescha il server local per empruvar els.
Make it yours.|Mach es zu deinem.|Créez votre espace.|Crea il tuo spazio.|Crea tes spazi.
Recover your account.|Konto wiederherstellen.|Récupérez votre compte.|Recupera il tuo account.|Restaurescha tes conto.
Welcome back.|Willkommen zurück.|Bon retour.|Bentornato.|Bainvegni enavos.
Save private spots across Switzerland. Your locations and notes are visible only to you.|Speichere private Orte in der ganzen Schweiz. Deine Orte und Notizen sind nur für dich sichtbar.|Enregistrez des coins privés dans toute la Suisse. Vos lieux et notes ne sont visibles que par vous.|Salva luoghi privati in tutta la Svizzera. Luoghi e note sono visibili solo a te.|Memorisescha lieus privats en l’entira Svizra. Tes lieus e tias notizias èn visibels mo per tai.
Username|Benutzername|Nom d’utilisateur|Nome utente|Num d’utilisader
Recovery code|Wiederherstellungscode|Code de récupération|Codice di recupero|Code da restabiliment
New password|Neues Passwort|Nouveau mot de passe|Nuova password|Nov pled-clav
Password|Passwort|Mot de passe|Password|Pled-clav
At least 12 characters. No email address required.|Mindestens 12 Zeichen. Keine E-Mail-Adresse nötig.|Au moins 12 caractères. Aucune adresse e-mail requise.|Almeno 12 caratteri. Nessun indirizzo e-mail richiesto.|Almain 12 segns. Nagina adressa dad e-mail necessaria.
Create account|Konto erstellen|Créer un compte|Crea account|Crear in conto
Create an account|Konto erstellen|Créer un compte|Crea un account|Crear in conto
Reset password|Passwort zurücksetzen|Réinitialiser le mot de passe|Reimposta la password|Redefinir il pled-clav
Sign in|Anmelden|Se connecter|Accedi|S’annunziar
Sign in instead|Stattdessen anmelden|Se connecter plutôt|Accedi invece|S’annunziar empè
Use a recovery code|Wiederherstellungscode verwenden|Utiliser un code de récupération|Usa un codice di recupero|Duvrar in code da restabiliment
PRIVATE TO|PRIVAT FÜR|PRIVÉ POUR|PRIVATO PER|PRIVAT PER
Save your recovery code now|Wiederherstellungscode jetzt sichern|Conservez votre code de récupération|Conserva il codice di recupero|Memorisescha tes code da restabiliment
This is your only password-recovery method. Store it somewhere safe. It is shown only once.|Dies ist deine einzige Möglichkeit zur Passwortwiederherstellung. Bewahre den Code sicher auf. Er wird nur einmal angezeigt.|C’est votre seul moyen de récupérer le mot de passe. Conservez-le en lieu sûr. Il n’est affiché qu’une fois.|È l’unico modo per recuperare la password. Conservalo al sicuro. Viene mostrato una sola volta.|Quai è l’unica moda da restabilir tes pled-clav. Conserva il code en in lieu segir. El vegn mussà mo ina giada.
I saved it|Ich habe ihn gesichert|Je l’ai conservé|L’ho conservato|Jau hai memorisà el
Save selected forest cell|Ausgewählte Waldzelle speichern|Enregistrer la cellule choisie|Salva la cella selezionata|Memorisar la cella tschernida
{count} / 500 spots · private by default|{count} / 500 Orte · standardmässig privat|{count} / 500 coins · privés par défaut|{count} / 500 luoghi · privati per impostazione predefinita|{count} / 500 lieus · privats sco standard
Edit|Bearbeiten|Modifier|Modifica|Modifitgar
Delete|Löschen|Supprimer|Elimina|Stizzar
No saved spots yet. Choose a forest on the map, then save it here.|Noch keine Orte gespeichert. Wähle einen Wald auf der Karte und speichere ihn hier.|Aucun coin enregistré. Choisissez une forêt sur la carte, puis enregistrez-la ici.|Nessun luogo salvato. Scegli un bosco sulla mappa, poi salvalo qui.|Anc nagins lieus memorisads. Tscherna in guaud sin la charta e memorisescha el qua.
Export my spots|Meine Orte exportieren|Exporter mes coins|Esporta i miei luoghi|Exportar mes lieus
Sign out|Abmelden|Se déconnecter|Esci|Sa deconnectar
Delete account|Konto löschen|Supprimer le compte|Elimina account|Stizzar il conto
Choose a forest cell on the map first.|Wähle zuerst eine Waldzelle auf der Karte.|Choisissez d’abord une cellule forestière sur la carte.|Scegli prima una cella forestale sulla mappa.|Tscherna l’emprim ina cella da guaud sin la charta.
Delete this saved spot?|Diesen gespeicherten Ort löschen?|Supprimer ce coin enregistré ?|Eliminare questo luogo salvato?|Stizzar quest lieu memorisà?
Delete your account?|Dein Konto löschen?|Supprimer votre compte ?|Eliminare il tuo account?|Stizzar tes conto?
This permanently deletes your account, saved spots and sessions. Export your spots first if you want a copy.|Dies löscht dein Konto, deine Orte und Sitzungen dauerhaft. Exportiere zuerst deine Orte, wenn du eine Kopie möchtest.|Votre compte, vos coins et vos sessions seront supprimés définitivement. Exportez vos coins si vous souhaitez une copie.|Account, luoghi e sessioni saranno eliminati definitivamente. Esporta prima i luoghi se vuoi una copia.|Tes conto, lieus e sessiuns vegnan stizzads definitivamain. Exportescha l’emprim tes lieus sche ti vuls ina copia.
Confirm your password|Passwort bestätigen|Confirmez votre mot de passe|Conferma la password|Conferma tes pled-clav
Permanently delete account|Konto dauerhaft löschen|Supprimer définitivement le compte|Elimina definitivamente l’account|Stizzar definitivamain il conto
Cancel|Abbrechen|Annuler|Annulla|Interrumper
Edit spot|Ort bearbeiten|Modifier le coin|Modifica il luogo|Modifitgar il lieu
Save this forest.|Diesen Wald speichern.|Enregistrer cette forêt.|Salva questo bosco.|Memorisar quest guaud.
This location stays private to your account.|Dieser Ort bleibt in deinem Konto privat.|Ce lieu reste privé dans votre compte.|Questo luogo rimane privato nel tuo account.|Quest lieu resta privat en tes conto.
Name|Name|Nom|Nome|Num
Notes|Notizen|Notes|Note|Notizias
Save spot|Ort speichern|Enregistrer le coin|Salva il luogo|Memorisar il lieu
Please try again.|Bitte erneut versuchen.|Veuillez réessayer.|Riprova.|Emprova danovamain.
Not available|Nicht verfügbar|Indisponible|Non disponibile|Betg disponibel
Tree mix unavailable|Baumartenmix unbekannt|Mélange d’essences inconnu|Composizione sconosciuta|Maschaida da plantas nunenconuschenta
Conifer forest|Nadelwald|Forêt de résineux|Bosco di conifere|Guaud da coniferas
Broadleaf forest|Laubwald|Forêt de feuillus|Bosco di latifoglie|Guaud da feglia
Mixed forest|Mischwald|Forêt mixte|Bosco misto|Guaud maschadà
Stronger habitat signal|Stärkeres Habitat-Signal|Indice d’habitat plus fort|Segnale dell’habitat più forte|Signal da l’habitat pli ferm
Moderate habitat signal|Mittleres Habitat-Signal|Indice d’habitat modéré|Segnale dell’habitat moderato|Signal da l’habitat moderà
Lower habitat signal|Schwächeres Habitat-Signal|Indice d’habitat plus faible|Segnale dell’habitat più debole|Signal da l’habitat pli flaivel
Closed season today|Heute Schonzeit|Période de protection aujourd’hui|Oggi periodo di divieto|Oz temp da protecziun
Collect with care today|Heute achtsam sammeln|Cueillir avec précaution aujourd’hui|Oggi raccogli con attenzione|Rimnar cun precauziun oz
No mushroom collecting from the 1st through the 10th of each month in Zürich canton. You can still explore and observe.|Im Kanton Zürich ist das Pilzsammeln vom 1. bis 10. jedes Monats verboten. Erkunden und Beobachten bleibt möglich.|Dans le canton de Zurich, la cueillette est interdite du 1er au 10 de chaque mois. Vous pouvez toujours explorer et observer.|Nel canton Zurigo la raccolta è vietata dal 1° al 10 di ogni mese. Puoi comunque esplorare e osservare.|En il chantun Turitg è la racolta scumandada dal 1. fin il 10. da mintga mais. Ti pos tuttina explorar ed observar.
Maximum 1 kg per person per day. Collecting is prohibited in nature reserves; always check the rules at your location.|Höchstens 1 kg pro Person und Tag. In Naturschutzgebieten ist Sammeln verboten; prüfe immer die Regeln vor Ort.|Maximum 1 kg par personne et par jour. La cueillette est interdite dans les réserves naturelles ; vérifiez toujours les règles locales.|Massimo 1 kg per persona al giorno. La raccolta è vietata nelle riserve naturali; verifica sempre le norme locali.|Maximalmain 1 kg per persuna e di. En reservas natiralas è la racolta scumandada; controllescha adina las reglas localas.
Check local collecting rules|Lokale Sammelregeln prüfen|Vérifier les règles locales|Verifica le norme locali|Controllar las reglas localas
Rules differ across Switzerland. Check cantonal, municipal and protected-area restrictions. This habitat score does not establish collection permission.|Die Regeln unterscheiden sich in der Schweiz. Prüfe kantonale, kommunale und Schutzgebietsregeln. Die Bewertung erteilt keine Sammelerlaubnis.|Les règles diffèrent en Suisse. Vérifiez les restrictions cantonales, communales et des zones protégées. Ce score n’autorise pas la cueillette.|Le norme variano in Svizzera. Verifica le restrizioni cantonali, comunali e delle aree protette. Questo punteggio non autorizza la raccolta.|Las reglas varieschan en Svizra. Controllescha las restricziuns chantunalas, communalas e dals territoris protegids. Questa valitaziun na dat nagina permissiun da racolta.
{count} CELLS|{count} ZELLEN|{count} CELLULES|{count} CELLE|{count} CELLAS
{value}° slope|{value}° Neigung|{value}° de pente|{value}° di pendenza|{value}° pendenza
No mapped forest cells here. Pan the map, clear the search, or choose “Whole canton”.|Hier gibt es keine kartierten Waldzellen. Verschiebe die Karte, lösche die Suche oder wähle «Ganze Region».|Aucune cellule forestière ici. Déplacez la carte, effacez la recherche ou choisissez « Toute la région ».|Nessuna cella forestale qui. Sposta la mappa, cancella la ricerca o scegli «Tutta la regione».|Naginas cellas da guaud qua. Sposta la charta, stizza la tschertga u tscherna «Entira regiun».
FOREST CELL|WALDZELLE|CELLULE FORESTIÈRE|CELLA FORESTALE|CELLA DA GUAUD
{area} ha mapped forest|{area} ha kartierter Wald|{area} ha de forêt cartographiée|{area} ha di bosco cartografato|{area} ha guaud cartografà
MODELED SUITABILITY|MODELLIERTE EIGNUNG|APTITUDE MODÉLISÉE|IDONEITÀ MODELLATA|ADATTAZIUN MODELADA
weather included|Wetter berücksichtigt|météo incluse|meteo incluso|aura inclusa
habitat & terrain only|nur Habitat und Gelände|habitat et relief seuls|solo habitat e terreno|mo habitat e terren
CHECK LOCAL PROTECTION RULES|LOKALE SCHUTZREGELN PRÜFEN|VÉRIFIER LES RÈGLES DE PROTECTION|VERIFICA LE NORME DI PROTEZIONE|CONTROLLAR LAS REGLAS DA PROTECZIUN
Protection coverage is incomplete. Collecting may be forbidden in mapped areas and elsewhere. Check local rules before collecting.|Die Schutzgebietskarte ist unvollständig. Sammeln kann in kartierten Gebieten und anderswo verboten sein. Prüfe die lokalen Regeln.|La couverture des protections est incomplète. La cueillette peut être interdite dans les zones cartographiées et ailleurs. Vérifiez les règles locales.|La copertura delle protezioni è incompleta. La raccolta può essere vietata nelle aree cartografate e altrove. Verifica le norme locali.|La cuverta dals territoris protegids è incumpletta. La racolta po esser scumandada en territoris cartografads ed auters. Controllescha las reglas localas.
COLLECTING MAY BE FORBIDDEN|SAMMELN KANN VERBOTEN SEIN|LA CUEILLETTE PEUT ÊTRE INTERDITE|LA RACCOLTA PUÒ ESSERE VIETATA|LA RACOLTA PO ESSER SCUMANDADA
This cell overlaps a mapped forest reserve. Check the official rules before collecting; the score describes habitat suitability only.|Diese Zelle überschneidet sich mit einem kartierten Waldreservat. Prüfe die offiziellen Regeln; die Bewertung beschreibt nur die Habitateignung.|Cette cellule recoupe une réserve forestière. Vérifiez les règles officielles ; le score décrit uniquement l’aptitude de l’habitat.|Questa cella si sovrappone a una riserva forestale. Verifica le norme ufficiali; il punteggio descrive solo l’idoneità dell’habitat.|Questa cella sa cruscha cun ina reserva da guaud. Controllescha las reglas uffizialas; la valitaziun descriva mo l’adattaziun da l’habitat.
WHAT DRIVES IT?|WAS STECKT DAHINTER?|QUELS FACTEURS ?|QUALI FATTORI?|TGE FACTURS?
{count} / 6 FACTORS|{count} / 6 FAKTOREN|{count} / 6 FACTEURS|{count} / 6 FATTORI|{count} / 6 FACTURS
Tree partners|Baumpartner|Arbres partenaires|Alberi ospiti|Partenaris da plantas
Forest edge proxy|Waldrand-Näherung|Indicateur de lisière|Indicatore del margine|Indicatur da l’ur dal guaud
{value}% pine|{value}% Kiefer|{value}% de pins|{value}% di pino|{value}% tieu
mapped host tree|kartierter Wirtsbaum|arbre hôte cartographié|albero ospite cartografato|planta partenaria cartografada
{value}% broadleaf|{value}% Laubholz|{value}% de feuillus|{value}% di latifoglie|{value}% plantas da feglia
{value}% conifer|{value}% Nadelholz|{value}% de résineux|{value}% di conifere|{value}% coniferas
{value}% forest coverage in this {size} m cell|{value}% Waldanteil in dieser {size}-m-Zelle|{value}% de forêt dans cette cellule de {size} m|{value}% di bosco in questa cella di {size} m|{value}% guaud en questa cella da {size} m
Canopy & forest coverage|Kronendeckung und Waldanteil|Couvert et surface forestière|Copertura e superficie forestale|Cuverta da tschimas e guaud
{value}% canopy|{value}% Kronendeckung|{value}% de couvert|{value}% di copertura|{value}% cuverta da tschimas
{value}% of {size} m cell is forest|{value}% der {size}-m-Zelle ist Wald|{value}% de la cellule de {size} m est boisé|{value}% della cella di {size} m è bosco|{value}% da la cella da {size} m è guaud
Moisture|Feuchtigkeit|Humidité|Umidità|Umiditad
Temperature|Temperatur|Température|Temperatura|Temperatura
Weather unavailable; this factor is omitted.|Wetter nicht verfügbar; dieser Faktor wird ausgelassen.|Météo indisponible ; ce facteur est omis.|Meteo non disponibile; questo fattore è omesso.|Aura betg disponibla; quest factur vegn omess.
Weather unavailable|Wetter nicht verfügbar|Météo indisponible|Meteo non disponibile|Aura betg disponibla
{value} mm / 14 days|{value} mm / 14 Tage|{value} mm / 14 jours|{value} mm / 14 giorni|{value} mm / 14 dis
{value} m³/m³ soil water|{value} m³/m³ Bodenwasser|{value} m³/m³ d’eau du sol|{value} m³/m³ d’acqua nel suolo|{value} m³/m³ aua dal terren
{value}°C · past 7 days|{value}°C · letzte 7 Tage|{value}°C · 7 derniers jours|{value}°C · ultimi 7 giorni|{value}°C · ultims 7 dis
Slope & aspect|Neigung und Exposition|Pente et exposition|Pendenza ed esposizione|Pendenza ed exposiziun
{value}° median slope|{value}° mittlere Neigung|{value}° de pente médiane|{value}° di pendenza mediana|{value}° pendenza mediana
{direction} aspect|Exposition {direction}|exposition {direction}|esposizione {direction}|exposiziun {direction}
Season|Saison|Saison|Stagione|Stagiun
SUN & DRYING|SONNE UND AUSTROCKNUNG|SOLEIL ET ASSÈCHEMENT|SOLE E DISSECCAMENTO|SULEGL E SIENTADA
{value} h sunshine / 7 days|{value} h Sonne / 7 Tage|{value} h de soleil / 7 jours|{value} h di sole / 7 giorni|{value} h sulegl / 7 dis
{value} mm reference evaporation / 14 days|{value} mm Referenzverdunstung / 14 Tage|{value} mm d’évaporation de référence / 14 jours|{value} mm di evaporazione di riferimento / 14 giorni|{value} mm evaporaziun da referenza / 14 dis
Sunshine and drying data unavailable|Sonnen- und Austrocknungsdaten nicht verfügbar|Données de soleil et d’assèchement indisponibles|Dati su sole e disseccamento non disponibili|Datas da sulegl e sientada betg disponiblas
Weather inputs blend regional anchors; they are not local forest measurements. Sunshine is not light reaching the forest floor. Reference evaporation modestly reduces the rainfall contribution; canopy and aspect already represent shelter.|Wetterdaten werden aus regionalen Punkten gemischt; sie sind keine lokalen Waldmessungen. Sonnenstunden messen nicht das Licht am Waldboden. Referenzverdunstung reduziert den Regenbeitrag leicht; Kronendeckung und Exposition stehen bereits für Schutz.|Les données combinent des points régionaux, pas des mesures locales en forêt. L’ensoleillement ne mesure pas la lumière au sol. L’évaporation de référence réduit légèrement l’apport de pluie ; couvert et exposition représentent déjà l’abri.|I dati combinano punti regionali, non misure locali nel bosco. Il soleggiamento non misura la luce al suolo. L’evaporazione di riferimento riduce lievemente il contributo della pioggia; copertura ed esposizione rappresentano già il riparo.|Las datas maschaidan puncts regiunals, betg mesiraziuns localas en il guaud. Las uras da sulegl na mesiran betg la glisch al funs. L’evaporaziun da referenza reducescha levamain la contribuziun da plievgia; cuverta ed exposiziun represchentan gia il refugi.
TRACEABLE TO THE SOURCE|BIS ZUR QUELLE NACHVOLLZIEHBAR|TRAÇABLE À LA SOURCE|TRACCIABILE ALLA FONTE|TRACABEL FIN A LA FUNTAUNA
Forest source {year} · terrain {size} m. Cell {id}, {lat}° N, {lon}° E.|Waldquelle {year} · Gelände {size} m. Zelle {id}, {lat}° N, {lon}° E.|Source forestière {year} · relief {size} m. Cellule {id}, {lat}° N, {lon}° E.|Fonte forestale {year} · terreno {size} m. Cella {id}, {lat}° N, {lon}° E.|Funtauna dal guaud {year} · terren {size} m. Cella {id}, {lat}° N, {lon}° E.
{size} m score · {mask} m forest mask. This is a habitat estimate, not a sighting or collection permission.|{size}-m-Bewertung · {mask}-m-Waldmaske. Eine Habitatschätzung, kein Fund und keine Sammelerlaubnis.|Score à {size} m · masque forestier à {mask} m. Estimation d’habitat, pas une observation ni une autorisation de cueillette.|Punteggio a {size} m · maschera forestale a {mask} m. Una stima dell’habitat, non un avvistamento né un permesso di raccolta.|Valitaziun da {size} m · mascra da guaud da {mask} m. Ina stimaziun da l’habitat, betg in chat u ina permissiun da racolta.
Explore this forest|Diesen Wald erkunden|Explorer cette forêt|Esplora questo bosco|Explorar quest guaud
Loading weather…|Wetter wird geladen…|Chargement météo…|Caricamento meteo…|Chargiar l’aura…
Weather snapshot|Wetterstand|Instantané météo|Dati meteo|Datas da l’aura
Weather refreshed|Wetter aktualisiert|Météo actualisée|Meteo aggiornato|Aura actualisada
Recent weather · cached|Aktuelles Wetter · gespeichert|Météo récente · en cache|Meteo recente · memorizzato|Aura recenta · memorisada
Partial weather coverage|Teilweise Wetterabdeckung|Couverture météo partielle|Copertura meteo parziale|Cuverta parziala da l’aura
Habitat & terrain only|Nur Habitat und Gelände|Habitat et relief seuls|Solo habitat e terreno|Mo habitat e terren
Offline basemap|Offline-Grundkarte|Fond de carte hors ligne|Mappa di base offline|Charta da basa offline
{size} m forest scores|{size}-m-Waldbewertungen|scores forestiers à {size} m|punteggi forestali a {size} m|valitaziuns dal guaud da {size} m
{size} overview|{size} Übersicht|vue d’ensemble à {size}|panoramica a {size}|survista da {size}
zoom for {size} m detail|zoomen für {size}-m-Details|zoomez pour les détails à {size} m|ingrandisci per dettagli a {size} m|zooma per detagls da {size} m
{size} forest summary|{size} Waldübersicht|résumé forestier à {size}|sintesi forestale a {size}|resumaziun dal guaud da {size}
Area-weighted mean of {count} cells|Flächengewichteter Mittelwert aus {count} Zellen|Moyenne pondérée par la surface de {count} cellules|Media ponderata per superficie di {count} celle|Media tenor surfatscha da {count} cellas
click to zoom|zum Zoomen klicken|cliquez pour zoomer|clicca per ingrandire|clicca per zoomar
click to inspect|zum Prüfen klicken|cliquez pour consulter|clicca per esaminare|clicca per examinar
mapped protected area|kartiertes Schutzgebiet|zone protégée cartographiée|area protetta cartografata|territori protegì cartografà
Mapped protected area|Kartiertes Schutzgebiet|Zone protégée cartographiée|Area protetta cartografata|Territori protegì cartografà
Collecting may be forbidden here. Habitat scores describe growing conditions, not permission to collect. Check the official reserve rules before collecting.|Hier kann Sammeln verboten sein. Habitatbewertungen beschreiben Wachstumsbedingungen, keine Sammelerlaubnis. Prüfe die offiziellen Schutzgebietsregeln.|La cueillette peut être interdite ici. Les scores décrivent les conditions de croissance, pas une permission. Vérifiez les règles officielles de la réserve.|Qui la raccolta può essere vietata. I punteggi descrivono le condizioni di crescita, non un permesso. Verifica le norme ufficiali della riserva.|Qua po la racolta esser scumandada. Las valitaziuns descrivan cundiziuns da creschientscha, betg ina permissiun. Controllescha las reglas uffizialas da la reserva.
{id}. Boundaries simplified for display; other protections may apply outside this layer.|{id}. Grenzen vereinfacht; weitere Schutzregeln können ausserhalb dieser Ebene gelten.|{id}. Limites simplifiées ; d’autres protections peuvent s’appliquer hors de cette couche.|{id}. Confini semplificati; altre protezioni possono valere fuori da questo livello.|{id}. Cunfins simplifitgads; ulteriuras protecziuns pon valair ordaifer questa stresa.
Check the official map ↗|Offizielle Karte prüfen ↗|Consulter la carte officielle ↗|Consulta la mappa ufficiale ↗|Consultar la charta uffiziala ↗
{count} mapped areas · collecting may be forbidden in hatched areas|{count} kartierte Gebiete · in schraffierten Flächen kann Sammeln verboten sein|{count} zones cartographiées · cueillette potentiellement interdite dans les zones hachurées|{count} aree cartografate · raccolta potenzialmente vietata nelle aree tratteggiate|{count} territoris cartografads · racolta eventualmain scumandada en las surfatschas strivladas
Reserve boundaries unavailable — protection coverage is not shown.|Schutzgebietsgrenzen nicht verfügbar — Schutzgebiete werden nicht angezeigt.|Limites indisponibles — les protections ne sont pas affichées.|Confini non disponibili — le protezioni non sono visualizzate.|Cunfins betg disponibels — las protecziuns na vegnan betg mussadas.
Shared weather unavailable. Try again later.|Gemeinsame Wetterdaten nicht verfügbar. Versuche es später erneut.|Météo partagée indisponible. Réessayez plus tard.|Meteo condiviso non disponibile. Riprova più tardi.|Datas communablas da l’aura betg disponiblas. Emprova pli tard.
The map could not load. Reload to try again.|Die Karte konnte nicht geladen werden. Lade die Seite erneut.|La carte n’a pas pu être chargée. Rechargez la page.|Impossibile caricare la mappa. Ricarica la pagina.|La charta n’ha betg pudì vegnir chargiada. Chargia danovamain la pagina.
Forest data could not load. Please reload using a current browser.|Walddaten konnten nicht geladen werden. Lade mit einem aktuellen Browser erneut.|Les données forestières n’ont pas pu être chargées. Rechargez avec un navigateur récent.|Impossibile caricare i dati forestali. Ricarica con un browser aggiornato.|Las datas dal guaud n’han betg pudì vegnir chargiadas. Chargia danovamain cun in navigatur actual.
The forest dataset could not load. Reload the page to try again.|Der Walddatensatz konnte nicht geladen werden. Lade die Seite erneut.|Le jeu de données forestières n’a pas pu être chargé. Rechargez la page.|Impossibile caricare i dati forestali. Ricarica la pagina.|Las datas dal guaud n’han betg pudì vegnir chargiadas. Chargia danovamain la pagina.
Zoom in|Vergrössern|Zoom avant|Ingrandisci|Engrondir
Zoom out|Verkleinern|Zoom arrière|Riduci|Empitschnir
Close popup|Popup schliessen|Fermer la fenêtre|Chiudi finestra|Serrar la fanestra
Basemap, forest & terrain:|Grundkarte, Wald und Gelände:|Fond de carte, forêt et relief :|Mappa di base, boschi e terreno:|Charta da basa, guaud e terren:
OpenStreetMap contributors|OpenStreetMap-Mitwirkende|contributeurs OpenStreetMap|contributori OpenStreetMap|contribuents OpenStreetMap
`.trim().split('\n').map(line=>line.split('|')));
window.SHROOMS_MESSAGES.push(...String.raw`
Explore Switzerland using a 500-metre national overview, 100-metre canton detail, and 50-metre detail in Zürich. Scores use mapped forest, regional weather and the available terrain and tree data. Zürich tree composition and canopy come from aerial forest surveys; elsewhere tree mix comes from the national forest inventory. Zürich terrain uses 50 m samples; nationwide terrain comes from DHM25/200. National canopy and individual host-tree shares are unavailable and omitted. Recent rain, soil moisture, humidity and temperature come from Open-Meteo.|Entdecke die Schweiz mit 500-m-Landesübersicht, 100-m-Kantonsdetails und 50-m-Details in Zürich. Bewertungen nutzen kartierten Wald, regionales Wetter sowie verfügbare Gelände- und Baumdaten. In Zürich stammen Baumarten und Kronendeckung aus Luftbildaufnahmen, andernorts der Baumartenmix aus dem Landesforstinventar. Zürichs Gelände nutzt 50-m-Stichproben, landesweit dient DHM25/200 als Grundlage. Nationale Kronendeckung und einzelne Wirtsbaumanteile fehlen und werden ausgelassen. Regen, Boden- und Luftfeuchtigkeit sowie Temperatur kommen von Open-Meteo.|Explorez la Suisse avec une vue nationale à 500 m, des détails cantonaux à 100 m et à 50 m à Zurich. Les scores utilisent les forêts cartographiées, la météo régionale et les données disponibles sur le relief et les arbres. À Zurich, essences et couvert viennent de relevés aériens ; ailleurs, le mélange vient de l’inventaire forestier national. Le relief zurichois utilise des échantillons à 50 m, le relief national DHM25/200. Le couvert national et les parts d’arbres hôtes individuels sont indisponibles et omis. Pluie, humidité du sol et de l’air et température viennent d’Open-Meteo.|Esplora la Svizzera con una panoramica nazionale a 500 m, dettagli cantonali a 100 m e a 50 m a Zurigo. I punteggi usano boschi cartografati, meteo regionale e dati disponibili su terreno e alberi. A Zurigo, composizione e copertura provengono da rilievi aerei; altrove la composizione viene dall’inventario forestale nazionale. Il terreno zurighese usa campioni a 50 m, quello nazionale DHM25/200. Copertura nazionale e quote di singoli alberi ospiti non sono disponibili e sono omesse. Pioggia, umidità e temperatura provengono da Open-Meteo.|Explorescha la Svizra cun ina survista naziunala da 500 m, detagls chantunals da 100 m e da 50 m a Turitg. Las valitaziuns dovran guaud cartografà, aura regiunala e datas disponiblas da terren e plantas. A Turitg derivan las plantas e la cuverta da fotografias or da l’aria; auter vegn la maschaida da l’inventari forestal naziunal. Il terren da Turitg dovra provas da 50 m, quel naziunal DHM25/200. La cuverta naziunala e las parts da singulas plantas partenarias mancan e vegnan omessas. Plievgia, umiditad e temperatura derivan dad Open-Meteo.
The ecological weights are provisional assumptions. They have not been trained or validated against mushroom observations. Weather represents a wider area; a fine forest cell is not a local weather measurement. Missing inputs are omitted and shown in the details.|Die ökologischen Gewichte sind vorläufige Annahmen, nicht anhand von Pilzfunden trainiert oder validiert. Wetterdaten stehen für grössere Gebiete; eine feine Waldzelle ist keine lokale Wettermessung. Fehlende Werte werden ausgelassen und in den Details ausgewiesen.|Les pondérations écologiques sont provisoires, ni entraînées ni validées par des observations de champignons. La météo représente une zone plus large ; une cellule fine n’est pas une mesure météo locale. Les données manquantes sont omises et signalées.|I pesi ecologici sono ipotesi provvisorie, non addestrate né validate con osservazioni di funghi. Il meteo rappresenta aree più vaste; una cella fine non è una misura meteo locale. I dati mancanti sono omessi e indicati.|Las paisas ecologicas èn supposiziuns provisorias, betg trenadas u validadas cun observaziuns da bulieus. L’aura represchenta territoris pli gronds; ina cella fina n’è betg ina mesiraziun locala da l’aura. Datas mancantas vegnan omessas ed inditgadas.
The score is a weighted geometric mean: tree partners (forest-edge proxy for Parasol) 20%, canopy 10%, moisture 35%, temperature 15%, terrain 10%, season 10%. Moisture combines soil water (50%), rainfall (30%) and air humidity (20%). Missing factors are omitted and the remaining weights normalized.|Die Bewertung ist ein gewichtetes geometrisches Mittel: Baumpartner (Waldrand-Näherung beim Riesenschirmling) 20%, Kronendeckung 10%, Feuchtigkeit 35%, Temperatur 15%, Gelände 10%, Saison 10%. Feuchtigkeit kombiniert Bodenwasser (50%), Regen (30%) und Luftfeuchtigkeit (20%). Fehlende Faktoren werden ausgelassen und die übrigen Gewichte normalisiert.|Le score est une moyenne géométrique pondérée : arbres partenaires (indicateur de lisière pour la coulemelle) 20%, couvert 10%, humidité 35%, température 15%, relief 10%, saison 10%. L’humidité combine eau du sol (50%), pluie (30%) et humidité de l’air (20%). Les facteurs manquants sont omis et les poids restants normalisés.|Il punteggio è una media geometrica ponderata: alberi ospiti (indicatore del margine per la mazza di tamburo) 20%, copertura 10%, umidità 35%, temperatura 15%, terreno 10%, stagione 10%. L’umidità combina acqua nel suolo (50%), pioggia (30%) e umidità dell’aria (20%). I fattori mancanti sono omessi e i pesi restanti normalizzati.|La valitaziun è ina media geometrica ponderada: plantas partenarias (indicatur da l’ur per Macrolepiota procera) 20%, cuverta 10%, umiditad 35%, temperatura 15%, terren 10%, stagiun 10%. L’umiditad cumbinescha aua dal terren (50%), plievgia (30%) ed umiditad da l’aria (20%). Facturs mancants vegnan omess e las paisas restantas normalisadas.
Gentler slopes and north-facing terrain receive a modest moisture-retention preference. Those are assumptions, not measured mushroom responses. Sunshine is shown as regional weather context. Reference evaporation reduces the rainfall contribution as a provisional drying proxy; it is not measured forest evaporation. Canopy and aspect represent local shelter. Soil acidity, deadwood, fungal presence, picking pressure, frost damage and fine-scale microclimate are not yet modeled. Parasol habitat outside forests is not covered.|Flache Hänge und Nordlagen erhalten einen kleinen Feuchtigkeitsbonus. Das sind Annahmen, keine gemessenen Pilzreaktionen. Sonnenstunden dienen als regionaler Kontext. Referenzverdunstung mindert den Regenbeitrag als vorläufiger Austrocknungsindikator, nicht als gemessene Waldverdunstung. Kronendeckung und Exposition stehen für Schutz. Bodensäure, Totholz, Pilzvorkommen, Sammeldruck, Frostschäden und lokales Mikroklima fehlen noch. Riesenschirmling-Habitate ausserhalb des Waldes sind nicht enthalten.|Les pentes douces et les versants nord reçoivent un léger avantage de rétention d’humidité. Ce sont des hypothèses, pas des réponses mesurées de champignons. Le soleil sert de contexte régional. L’évaporation de référence réduit l’apport de pluie comme indicateur provisoire de séchage, pas comme mesure forestière. Couvert et exposition représentent l’abri. Acidité, bois mort, présence fongique, pression de cueillette, gel et microclimat fin ne sont pas modélisés. Les habitats de la coulemelle hors forêt sont exclus.|Pendii dolci e versanti nord ricevono un modesto vantaggio di ritenzione idrica. Sono ipotesi, non risposte misurate dei funghi. Il sole è un dato regionale. L’evaporazione di riferimento riduce il contributo della pioggia come indicatore provvisorio di asciugamento, non come misura forestale. Copertura ed esposizione rappresentano il riparo. Acidità, legno morto, presenza fungina, pressione di raccolta, gelo e microclima fine non sono modellati. Sono esclusi gli habitat della mazza di tamburo fuori dal bosco.|Pendenzas levs e costas vers nord survegnan in pitschen avantatg per l’umiditad. Quai èn supposiziuns, betg reacziuns mesiradas da bulieus. Il sulegl serva sco context regiunal. L’evaporaziun da referenza reducescha la plievgia sco indicatur provisori da sientada, betg sco mesiraziun dal guaud. Cuverta ed exposiziun represchentan refugi. Aciditad, laina morta, preschientscha da bulieus, pressiun da racolta, donns da schelira e microclima fin na vegnan anc betg modelads. Habitats da Macrolepiota procera ordaifer il guaud èn exclus.
Zürich uses 50 m forest and terrain samples. Elsewhere, forest coverage is rasterized at 100 m and terrain comes from a 200 m source. Aerial survey years vary by location and appear on each cell. Mapped forest reserves retain their habitat scores and have a warning overlay. Collecting may be forbidden there; the map does not establish collection permission.|Zürich nutzt Wald- und Geländestichproben von 50 m. Anderswo wird Wald auf 100 m gerastert, das Gelände stammt aus einer 200-m-Quelle. Luftbildjahre variieren örtlich und werden pro Zelle angezeigt. Kartierte Waldreservate behalten ihre Bewertung und erhalten eine Warnüberlagerung. Sammeln kann dort verboten sein; die Karte erteilt keine Erlaubnis.|Zurich utilise des échantillons de forêt et de relief à 50 m. Ailleurs, la forêt est rasterisée à 100 m et le relief provient d’une source à 200 m. Les années de relevé aérien varient et figurent sur chaque cellule. Les réserves gardent leurs scores avec une couche d’avertissement. La cueillette peut y être interdite ; la carte ne l’autorise pas.|Zurigo usa campioni forestali e del terreno a 50 m. Altrove il bosco è rasterizzato a 100 m e il terreno deriva da una fonte a 200 m. Gli anni dei rilievi aerei variano e sono mostrati per cella. Le riserve mantengono i punteggi con un avviso sovrapposto. La raccolta può essere vietata; la mappa non la autorizza.|Turitg dovra provas da guaud e terren da 50 m. Auter vegn il guaud rasterisà a 100 m ed il terren deriva d’ina funtauna da 200 m. Ils onns da las fotografias varieschan e vegnan mussads per cella. Las reservas mantegnan lur valitaziun cun in avertiment. La racolta po esser scumandada; la charta na dat nagina permissiun.
Porcini|Steinpilz|Cèpe de Bordeaux|Porcino|Boletus edulis
Chanterelle|Eierschwamm|Girolle|Gallinaccio|Cantharellus cibarius
Horn of plenty|Totentrompete|Trompette de la mort|Trombetta dei morti|Craterellus cornucopioides
Parasol|Riesenschirmling|Coulemelle|Mazza di tamburo|Macrolepiota procera
Bay bolete|Maronenröhrling|Bolet bai|Boleto baio|Imleria badia
Wood hedgehog|Semmelstoppelpilz|Pied-de-mouton|Steccherino dorato|Hydnum repandum
Saffron milkcap|Echter Reizker|Lactaire délicieux|Lattario delizioso|Lactarius deliciosus
Tree partners, a sheltered canopy and moisture after rain.|Baumpartner, schützende Kronendeckung und Feuchtigkeit nach Regen.|Arbres partenaires, couvert protecteur et humidité après la pluie.|Alberi ospiti, copertura riparata e umidità dopo la pioggia.|Plantas partenarias, cuverta protegida ed umiditad suenter plievgia.
Broadleaf or mixed forest. Soil acidity is not yet included.|Laub- oder Mischwald. Bodensäure ist noch nicht berücksichtigt.|Forêts de feuillus ou mixtes. L’acidité du sol n’est pas encore incluse.|Boschi di latifoglie o misti. L’acidità del suolo non è ancora inclusa.|Guaud da feglia u maschadà. L’aciditad dal terren n’è anc betg inclusa.
A preference for broadleaf woods, especially beech and oak.|Bevorzugt Laubwälder, besonders Buche und Eiche.|Préférence pour les feuillus, surtout hêtres et chênes.|Preferisce latifoglie, soprattutto faggi e querce.|Preferenza per guaud da feglia, surtut faus e ruvers.
More open canopy and forest edges. Open grassland is outside this forest map.|Offenere Kronendeckung und Waldränder. Offenes Grünland liegt ausserhalb dieser Waldkarte.|Couvert plus ouvert et lisières. Les prairies ne sont pas couvertes par cette carte forestière.|Copertura più aperta e margini del bosco. I prati aperti non sono inclusi nella mappa.|Cuverta pli averta ed urs dal guaud. Prads averts n’èn betg inclus en questa charta dal guaud.
Conifer and mixed woodland. Acidic soil preference is not yet mapped.|Nadel- und Mischwald. Die Vorliebe für saure Böden ist noch nicht kartiert.|Forêts de résineux et mixtes. La préférence pour les sols acides n’est pas cartographiée.|Boschi di conifere e misti. La preferenza per suoli acidi non è cartografata.|Guaud da coniferas e maschadà. La preferenza per terrens acids n’è anc betg cartografada.
Damp broadleaf and mixed woods; moss and leaf litter are not yet mapped.|Feuchte Laub- und Mischwälder; Moos und Laubstreu sind noch nicht kartiert.|Forêts humides de feuillus et mixtes ; mousses et litière ne sont pas cartographiées.|Boschi umidi di latifoglie e misti; muschio e lettiera non sono cartografati.|Guaud umid da feglia e maschadà; mistgel e feglia per terra n’èn anc betg cartografads.
Pine partner: uses mapped pine share, not general conifer cover. Soil chemistry is not yet included.|Kiefer als Partner: nutzt den kartierten Kiefernanteil, nicht den gesamten Nadelholzanteil. Bodenchemie fehlt noch.|Partenaire du pin : utilise sa proportion cartographiée, pas celle de tous les résineux. La chimie du sol n’est pas incluse.|Partner del pino: usa la quota di pini cartografata, non tutte le conifere. La chimica del suolo non è inclusa.|Partenari dal tieu: dovra la part cartografada da tieus, betg tut las coniferas. La chemia dal terren n’è anc betg inclusa.
Please try again in a moment.|Bitte versuche es in einem Moment erneut.|Réessayez dans un instant.|Riprova tra un momento.|Emprova danovamain en in mument.
Use a password between 12 and 128 characters.|Verwende ein Passwort mit 12 bis 128 Zeichen.|Utilisez un mot de passe de 12 à 128 caractères.|Usa una password tra 12 e 128 caratteri.|Dovra in pled-clav cun 12 fin 128 segns.
Use 3–32 letters, numbers or underscores for your username.|Verwende 3–32 Buchstaben, Zahlen oder Unterstriche als Benutzernamen.|Utilisez 3 à 32 lettres, chiffres ou tirets bas pour le nom d’utilisateur.|Usa 3–32 lettere, cifre o trattini bassi per il nome utente.|Dovra 3–32 bustabs, cifras u stritgs bass per il num d’utilisader.
That username is already taken.|Dieser Benutzername ist bereits vergeben.|Ce nom d’utilisateur est déjà pris.|Questo nome utente è già in uso.|Quest num d’utilisader è gia occupà.
Username or password is incorrect.|Benutzername oder Passwort ist falsch.|Nom d’utilisateur ou mot de passe incorrect.|Nome utente o password errati.|Num d’utilisader u pled-clav incorrect.
Username or recovery code is incorrect.|Benutzername oder Wiederherstellungscode ist falsch.|Nom d’utilisateur ou code de récupération incorrect.|Nome utente o codice di recupero errati.|Num d’utilisader u code da restabiliment incorrect.
Recovery code has already been used.|Der Wiederherstellungscode wurde bereits verwendet.|Ce code de récupération a déjà été utilisé.|Il codice di recupero è già stato usato.|Il code da restabiliment è gia vegnì duvrà.
Password is incorrect.|Das Passwort ist falsch.|Mot de passe incorrect.|Password errata.|Il pled-clav è incorrect.
You can save up to 500 spots.|Du kannst bis zu 500 Orte speichern.|Vous pouvez enregistrer jusqu’à 500 coins.|Puoi salvare fino a 500 luoghi.|Ti pos memorisar fin a 500 lieus.
Spot not found.|Ort nicht gefunden.|Coin introuvable.|Luogo non trovato.|Lieu betg chattà.
Invalid spot. Choose a Swiss map location, a name up to 100 characters and notes up to 2,000 characters.|Ungültiger Ort. Wähle einen Schweizer Kartenort, einen Namen bis 100 Zeichen und Notizen bis 2’000 Zeichen.|Lieu invalide. Choisissez un point en Suisse, un nom de 100 caractères au maximum et des notes de 2 000 caractères au maximum.|Luogo non valido. Scegli un punto in Svizzera, un nome di massimo 100 caratteri e note di massimo 2.000 caratteri.|Lieu nunvalid. Tscherna in punct en Svizra, in num cun maximalmain 100 segns e notizias cun maximalmain 2’000 segns.
Sign in to continue.|Melde dich an, um fortzufahren.|Connectez-vous pour continuer.|Accedi per continuare.|T’annunzia per cuntinuar.
Your session changed. Reload and try again.|Deine Sitzung hat sich geändert. Lade neu und versuche es erneut.|Votre session a changé. Rechargez et réessayez.|La sessione è cambiata. Ricarica e riprova.|Tia sessiun è sa midada. Chargia danovamain ed emprova anc ina giada.
Too many requests. Try again in a minute.|Zu viele Anfragen. Versuche es in einer Minute erneut.|Trop de demandes. Réessayez dans une minute.|Troppe richieste. Riprova tra un minuto.|Memia bleras dumondas. Emprova danovamain en ina minuta.
Server is busy. Try again shortly.|Der Server ist ausgelastet. Versuche es gleich erneut.|Le serveur est occupé. Réessayez bientôt.|Il server è occupato. Riprova tra poco.|Il server è occupà. Emprova bainbaud danovamain.
Something went wrong. Please try again.|Etwas ist schiefgelaufen. Bitte erneut versuchen.|Une erreur est survenue. Veuillez réessayer.|Si è verificato un errore. Riprova.|Igl ha dà in sbagl. Emprova danovamain.
Request failed.|Anfrage fehlgeschlagen.|Échec de la demande.|Richiesta non riuscita.|La dumonda n’è betg reussida.
Request origin is not allowed.|Die Anfrage stammt von einer nicht erlaubten Seite.|L’origine de la demande n’est pas autorisée.|L’origine della richiesta non è consentita.|L’origin da la dumonda n’è betg permess.
Request is too large.|Die Anfrage ist zu gross.|La demande est trop volumineuse.|La richiesta è troppo grande.|La dumonda è memia gronda.
Network connection unavailable. Please try again.|Keine Netzwerkverbindung. Bitte erneut versuchen.|Connexion réseau indisponible. Veuillez réessayer.|Connessione di rete non disponibile. Riprova.|Colliaziun da rait betg disponibla. Emprova danovamain.
`.trim().split('\n').map(line=>line.split('|')));
window.SHROOMS_MESSAGES.push(...String.raw`
Please complete this field.|Bitte fülle dieses Feld aus.|Veuillez remplir ce champ.|Compila questo campo.|Emplenescha quest champ.
Use at least {count} characters.|Verwende mindestens {count} Zeichen.|Utilisez au moins {count} caractères.|Usa almeno {count} caratteri.|Dovra almain {count} segns.
Please check this field.|Bitte prüfe dieses Feld.|Veuillez vérifier ce champ.|Controlla questo campo.|Controllescha quest champ.
Send JSON.|Die Anfrage muss JSON verwenden.|La demande doit utiliser JSON.|La richiesta deve usare JSON.|La dumonda sto duvrar JSON.
Invalid JSON.|Ungültige Anfrage.|Demande invalide.|Richiesta non valida.|Dumonda nunvalida.
Unknown species.|Unbekannte Pilzart.|Espèce inconnue.|Specie sconosciuta.|Spezia nunenconuschenta.
shrooms maps mushroom habitat across Switzerland using forest composition, canopy, slope and weather.|shrooms kartiert Pilzhabitate in der Schweiz anhand von Baumarten, Kronendeckung, Neigung und Wetter.|shrooms cartographie les habitats de champignons en Suisse à partir des essences, du couvert, de la pente et de la météo.|shrooms mappa gli habitat dei funghi in Svizzera usando composizione forestale, copertura, pendenza e meteo.|shrooms cartografescha habitats da bulieus en Svizra cun plantas, cuverta, pendenza ed aura.
`.trim().split('\n').map(line=>line.split('|')));
window.SHROOMS_MESSAGES.push(...String.raw`
Winter chanterelle|Trompetenpfifferling|Chanterelle en tube|Finferla|Craterellus tubaeformis
Slippery jack|Butterpilz|Bolet jaune|Pinarello|Suillus luteus
Spruce milkcap|Fichtenreizker|Lactaire des épicéas|Lattario dell’abete rosso|Lactarius deterrimus
Charcoal burner|Frauentäubling|Russule charbonnière|Colombina maggiore|Russula cyanoxantha
Late-season conifer woodland. Moss and acidic soil are not mapped; the canopy preference is provisional.|Nadelwald im Spätherbst. Moos und saure Böden sind nicht kartiert; die Kronendeckungspräferenz ist vorläufig.|Forêts de résineux en fin de saison. Mousses et sols acides ne sont pas cartographiés ; la préférence de couvert est provisoire.|Boschi di conifere a fine stagione. Muschio e suoli acidi non sono cartografati; la preferenza di copertura è provvisoria.|Guaud da coniferas a la fin da la stagiun. Mistgel e terrens acids n’èn betg cartografads; la preferenza da cuverta è provisoria.
Pine-associated woodland. Uses mapped pine share where available; soil chemistry and tree age are not mapped.|Wald mit Kiefern. Nutzt den kartierten Kiefernanteil, sofern vorhanden; Bodenchemie und Baumalter sind nicht kartiert.|Boisements associés aux pins. Utilise leur part cartographiée si disponible ; chimie du sol et âge des arbres non cartographiés.|Boschi associati ai pini. Usa la quota cartografata se disponibile; chimica del suolo ed età degli alberi non sono cartografate.|Guaud cun tieus. Dovra la part cartografada da tieus, sche disponibla; chemia dal terren e vegliadetgna da las plantas n’èn betg cartografadas.
Spruce partner: uses mapped spruce share, not general conifer cover. Soil chemistry is not mapped.|Fichte als Partner: nutzt den kartierten Fichtenanteil, nicht den gesamten Nadelholzanteil. Bodenchemie ist nicht kartiert.|Partenaire de l’épicéa : utilise sa part cartographiée, pas celle de tous les résineux. La chimie du sol n’est pas cartographiée.|Partner dell’abete rosso: usa la sua quota cartografata, non tutte le conifere. La chimica del suolo non è cartografata.|Partenari dal pign: dovra la part cartografada da pigns, betg tut las coniferas. La chemia dal terren n’è betg cartografada.
Broadleaf woodland, particularly beech and oak. Soil chemistry and leaf litter are not mapped.|Laubwald, besonders Buche und Eiche. Bodenchemie und Laubstreu sind nicht kartiert.|Forêts de feuillus, surtout hêtres et chênes. Chimie du sol et litière non cartographiées.|Boschi di latifoglie, soprattutto faggi e querce. Chimica del suolo e lettiera non sono cartografate.|Guaud da feglia, surtut faus e ruvers. Chemia dal terren e feglia per terra n’èn betg cartografadas.
Ecology & limits|Ökologie und Grenzen|Écologie et limites|Ecologia e limiti|Ecologia e cunfins
Ecological sources support habitat descriptions. Numerical settings remain provisional.|Ökologische Quellen stützen die Habitatbeschreibungen. Die Zahlenwerte bleiben vorläufig.|Les sources écologiques étayent les descriptions d’habitat. Les paramètres numériques restent provisoires.|Le fonti ecologiche sostengono le descrizioni degli habitat. I parametri numerici restano provvisori.|Las funtaunas ecologicas sustegnan las descripziuns dals habitats. Las valurs numericas restan provisorias.
Not modeled|Nicht modelliert|Non modélisé|Non modellato|Betg modelà
Soil chemistry|Bodenchemie|Chimie du sol|Chimica del suolo|Chemia dal terren
Soil acidity|Bodensäure|Acidité du sol|Acidità del suolo|Aciditad dal terren
Moss cover|Moosbedeckung|Couverture de mousses|Copertura di muschio|Cuverta da mistgel
Leaf litter|Laubstreu|Litière de feuilles|Lettiera di foglie|Feglia per terra
Tree age|Baumalter|Âge des arbres|Età degli alberi|Vegliadetgna da las plantas
Open grassland|Offenes Grünland|Prairies ouvertes|Prati aperti|Prads averts
{value}% spruce|{value}% Fichte|{value}% d’épicéas|{value}% di abete rosso|{value}% pign
{value}% beech|{value}% Buche|{value}% de hêtres|{value}% di faggio|{value}% fau
{value}% oak|{value}% Eiche|{value}% de chênes|{value}% di quercia|{value}% ruver
{value}% fir|{value}% Tanne|{value}% de sapins|{value}% di abete bianco|{value}% aviez
`.trim().split('\n').map(line=>line.split('|')));
